- app/controllers/organizations_controller.rb
- app/models/organization.rb
- app/models/user.rb
- app/views/organizations/show.html.slim
- db/migrate/20140908161521_remove_owner_id_from_organization.rb
- db/schema.rb
- spec/factories.rb
- spec/features/create_bank_account_spec.rb
- spec/features/create_organization_spec.rb
- spec/models/organization_spec.rb
- spec/models/user_spec.rb
https://trello.com/c/pwEMHyQR/9-remove-owner-id-field-from-organizations-table
> Remove owner_id from organizations

- app/helpers/layout_helper.rb
- app/views/shared/layout/_header.html.slim
- app/views/shared/layout/_switch_organization.html.slim
- spec/features/switch_organization_spec.rb
https://trello.com/c/DbEe2qy4/8-user-may-switch-current-organization-to-show
> Restyle organization switch

- app/models/invitation.rb
invitation.owner == '' if user owner deleted
> fix invitations bug

- app/assets/javascripts/transactions.js
Because datepicker autocorrects date fields
> remove unneeded masks

- app/models/transaction.rb
> fix amount_balance

- app/assets/javascripts/transactions.js
- app/assets/stylesheets/bank_accounts.css.scss
- app/assets/stylesheets/variables.css.scss
- app/controllers/home_controller.rb
- app/helpers/layout_helper.rb
- app/models/category.rb
- app/models/transaction.rb
- app/models/transfer.rb
- app/views/transactions/_form.html.slim
- app/views/transactions/_transaction.html.slim
- app/views/transactions/_transfer_form.html.slim
- app/views/transactions/create_transfer.js.erb
- db/migrate/20150817043620_add_transfer_id_to_transactions.rb
- db/migrate/20150817043620_add_transfer_out_id_to_transactions.rb
- db/schema.rb
- spec/factories.rb
- spec/features/categories_root_page_spec.rb
- spec/features/create_transfer_transaction_spec.rb
- spec/features/edit_transaction_spec.rb
- spec/features/transactions_filter_spec.rb
- spec/support/database_cleaner.rb
- spec/support/shared_examples/transaction_income_shared.rb
- spec/support/shared_examples/transaction_outcome_shared.rb
> transfer refactoring

- app/assets/stylesheets/common_responsive.css.scss
- app/views/shared/layout/_header.html.slim
- app/views/shared/layout/_total_balance.html.slim
https://trello.com/c/uS4Kh8RD/329--
> Fix mobile menu display

- app/controllers/invoices_controller.rb
- app/helpers/application_helper.rb
- app/helpers/invoices_helper.rb
- app/models/invoice.rb
- app/views/invoices/index.html.slim
- config/routes.rb
- spec/factories.rb
- spec/features/invoices/index_spec.rb
https://trello.com/c/lux8iJjk/328--
> Add ability to filter invoices

- app/views/invoices/edit.html.slim
- app/views/invoices/show.html.slim
https://trello.com/c/CVlK6H5h/324--
> Modify the breadcrumbs

- app/views/invoices/edit.html.slim
- spec/features/invoices/edit_spec.rb
https://trello.com/c/CVlK6H5h/324--
> Fix invoice link

- app/controllers/invoices_controller.rb
- app/helpers/application_helper.rb
- app/views/invoices/index.html.slim
- config/routes.rb
https://trello.com/c/lux8iJjk/328--
> Fix invoices tabs

- app/models/customer.rb
- app/models/organization.rb
- app/views/invoices/_debtor.html.slim
- app/views/invoices/_debtors.html.slim
- app/views/invoices/index.html.slim
- config/initializers/money.rb
- spec/features/invoices/index_spec.rb
- spec/models/organization_spec.rb
https://trello.com/c/Kh6s6PSD/321-total
> Invoices total

- app/assets/stylesheets/transactions.css.scss
https://trello.com/c/uS4Kh8RD/329--
> Fix transactions table display on iphone

- app/views/shared/layout/_header.html.slim
https://trello.com/c/vU2s5AYO/326-invoices-statistics
> Add invoices link

- app/controllers/invoices_controller.rb
- spec/features/invoices/index_spec.rb
https://trello.com/c/cZSZGNPU/323--
> Change invoices default order

- app/helpers/layout_helper.rb
- app/models/customer.rb
- app/views/invoices/_debtor.html.slim
- app/views/invoices/_debtors.html.slim
- spec/features/invoices/index_spec.rb
https://trello.com/c/Kh6s6PSD/321-total
> Amend the debtors display

- app/views/transactions/_transactions_table.html.slim
https://trello.com/c/uS4Kh8RD/329--
> Fix the transactions list display on mobile devices

- app/views/invoices/_invoice.html.slim
- app/views/invoices/index.html.slim
https://trello.com/c/cZSZGNPU/323--
> Amend invoices table

- app/views/transactions/_transactions_table.html.slim
https://trello.com/c/1SYcjJ7a/340--
> Fix font size

- app/views/shared/layout/_total_balance.html.slim
https://trello.com/c/xAoSrJDP/335-total
> Fix total sum

- lib/russian_central_bank_safe.rb
https://trello.com/c/YvsCudgB/333--
> Add timeout 2sec to russian_central_bank_safe

- app/models/invitation.rb
- spec/features/invite_user_spec.rb
https://trello.com/c/2IWIrdoc/312-new-invitation-500
> add validation messages for email on invitations page

- app/assets/javascripts/transactions.js
- spec/features/update_transaction_spec.rb
https://trello.com/c/SgPK7NS2/334-transfer-calculated-sum-rate
> Fix bug on transfer form with exchange rate with four decimal places

- app/helpers/layout_helper.rb
- app/models/organization.rb
- app/views/invoices/_debtors.html.slim
- spec/features/invoices/index_spec.rb
https://trello.com/c/MIoyFsIB/341--
> Add all customers and totlal summs to invoices index page

- app/assets/javascripts/statistics.js
- app/controllers/statistics_controller.rb
- app/models/balance_data_combainer.rb
- app/models/date_logic.rb
- app/models/organization.rb
- app/views/statistics/_periods_bar.html.slim
- spec/models/organization_spec.rb
https://trello.com/c/w6fbAgkb/297-balance
> Add ability of scaling balance graph

- app/controllers/invitations_controller.rb
- spec/features/invite_user_spec.rb
https://trello.com/c/toIpi8KW/302--
> Fix bug with invitations of created user, whrite some specs for this

- app/assets/javascripts/statistics.js
- app/controllers/statistics_controller.rb
- app/models/date_logic.rb
- app/models/organization.rb
- app/views/statistics/_periods_bar.html.slim
- config/routes.rb
- spec/models/organization_spec.rb
https://trello.com/c/0Ugft3oo/314-expense-income
> Add customers income/expense graph to statistics page

- app/views/statistics/_periods_bar.html.slim
https://trello.com/c/0Ugft3oo/314-expense-income
> Fix name of customers by month graph

- app/models/invoice_item.rb
https://trello.com/c/w5B8pZb1/300-new-invoice-hours
> Add allow_nil to hours of invoice_item

- app/views/invoices/_form.html.slim
- app/views/transactions/_form.html.slim
https://trello.com/c/l22SzGMM/349--
> Fix invoice customer_name and transaction date * on field

- app/controllers/users/registrations_controller.rb
- app/views/devise/registrations/edit.html.slim
https://trello.com/c/9NhQNELf/364-back
> Fix back link in profile edit page

- app/assets/stylesheets/transactions.scss
- app/views/transactions/_form.html.slim
- app/views/transactions/_transfer_form.html.slim
- config/initializers/simple_form_bootstrap3.rb
https://trello.com/c/TQtSAWvd/361-fix-style-for-leave-open-checkbox
> Fix live_open check_box in transaction and transfer forms

- app/views/transactions/_form.html.slim
- spec/features/update_transaction_spec.rb
https://trello.com/c/BH8iGeYn/366--
> Fix category list in transaction form on edit

- app/views/transactions/_form.html.slim
- spec/features/update_transaction_spec.rb
https://trello.com/c/zZVD6075/339--
> Fix create from invoice link in transaction form

- app/views/invoices/edit.html.slim
- app/views/invoices/new.html.slim
- app/views/invoices/show.html.slim
https://trello.com/c/foJtJBzS/365-sidebar-invoices
> Add debtors to all invoice views

- app/assets/javascripts/statistics.js
- app/assets/stylesheets/application.scss
- app/assets/stylesheets/loader.css
- app/assets/stylesheets/statistics.scss
- app/views/statistics/_periods_bar.html.slim
https://trello.com/c/w6fbAgkb/297-balance
> Fix balance scale

- app/assets/javascripts/statistics.js
- app/models/organization.rb
- app/views/statistics/_periods_bar.html.slim
https://trello.com/c/Fxrlz8AM/296-balance
> Fix balance pagination

- app/views/home/show.html.slim
https://trello.com/c/ogawqDFC/400--
> fix congratulation text

- app/assets/javascripts/statistics.js
- app/controllers/statistics_controller.rb
- app/views/statistics/_periods_bar.html.slim
https://trello.com/c/bI9rA02n/396-url
> Add steps and scales of Balance Graph to url params

- app/assets/stylesheets/common.scss
https://trello.com/c/a2wwd8xw/398--
> Fix font size for transaction list table

- app/models/organization.rb
- spec/models/organization_spec.rb
https://trello.com/c/jrRDnQc7/397-bug-with-next-step-blank-of-balancechart
> Fix bug with next step blank

- app/models/concerns/period.rb
- app/models/statistic_data/columns_chart.rb
- app/models/statistic_data/helpers.rb
https://trello.com/c/YBl58d1w/431--
> fix charts errors

- app/controllers/statistics_controller.rb
https://trello.com/c/YBl58d1w/431--
> Fix params names

- app/controllers/transactions_controller.rb
- spec/features/copy_transaction_spec.rb
https://trello.com/c/WmmnYzwi/436--
> Set current date in the copied transaction date field

- Gemfile
- Gemfile.lock
- db/seeds.rb
https://trello.com/c/zbK4RJ3c/432-create-seeds
> Seed organization and 150 transactions

- app/controllers/api/v1/bank_accounts_controller.rb
- app/controllers/api/v1/categories_controller.rb
- app/controllers/api/v1/customers_controller.rb
- app/controllers/api/v1/transactions_controller.rb
https://trello.com/c/A3GEg8mJ/426-%D0%BE%D1%88%D0%B8%D0%B1%D0%BA%D0%B0-bad-request-%D0%BF%D1%80%D0%B8-%D0%BF%D0%BE%D0%BF%D1%8B%D1%82%D0%BA%D0%B5-%D0%BE%D1%82%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BF%D1%83%D1%81%D1%82%D1%83%D1%8E-%D1%84%D0%BE%D1%80%D0%BC%D1%83-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8
> update api params

- app/controllers/api/v1/organizations_controller.rb
https://trello.com/c/cwNTt7Yq/447-update-redux-form
> fix organizations api controller

- app/views/api/v1/transactions/_transaction.json.jbuilder
- spec/requests/api/v1/transactions/create_spec.rb
- spec/requests/api/v1/transactions/create_transfer_spec.rb
- spec/requests/api/v1/transactions/destroy_spec.rb
- spec/requests/api/v1/transactions/index_spec.rb
- spec/requests/api/v1/transactions/show_spec.rb
- spec/requests/api/v1/transactions/update_spec.rb
https://trello.com/c/m6vPGJqd/469-transactions-%D0%BE%D0%B1%D0%BD%D0%BE%D0%B2%D0%B8%D1%82%D1%8C-%D1%81%D0%BF%D0%B8%D1%81%D0%BE%D0%BA-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B9
> update transactions amount serializeing

- app/controllers/api/v1/transactions_controller.rb
- app/models/transaction.rb
- app/views/api/v1/transactions/_transaction.json.jbuilder
- app/views/api/v1/transactions/_transfer_out.json.jbuilder
- spec/factories.rb
- spec/factories/transactions.rb
- spec/factories/transfers.rb
- spec/models/invitation_base_spec.rb
- spec/models/organization_invitation_spec.rb
- spec/models/unsubscribe_spec.rb
- spec/models/user_spec.rb
- spec/requests/api/v1/transactions/index_spec.rb
https://trello.com/c/7M8NqhwQ/474-transactions-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D1%80%D0%B5%D0%B4%D0%B0%D0%BA%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B9
> update transactions/transfers api

- config/initializers/money.rb
- spec/requests/api/v1/transactions/create_spec.rb
https://trello.com/c/fnJ9J8hq/480-%D0%B2-%D1%84%D0%BE%D1%80%D0%BC%D0%B5-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D1%8F-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%BD%D0%B5-%D1%80%D0%B0%D0%B1%D0%BE%D1%82%D0%B0%D0%B5%D1%82-%D0%BF%D0%BE%D0%BB%D0%B5-%D0%B2%D0%B2%D0%BE%D0%B4%D0%B0-amount
> fix transactions amount issue

- app/views/api/v1/bank_accounts/_bank_account.json.jbuilder
- spec/requests/api/v1/bank_accounts/create_spec.rb
- spec/requests/api/v1/bank_accounts/destroy_spec.rb
- spec/requests/api/v1/bank_accounts/index_spec.rb
- spec/requests/api/v1/bank_accounts/show_spec.rb
- spec/requests/api/v1/bank_accounts/update_spec.rb
https://trello.com/c/9QiVgZCV/471-make-component-to-select-bank-account
> update bank accounts api

- app/views/api/v1/organizations/total_balances.json.jbuilder
- spec/requests/api/v1/organizations/total_balances_spec.rb
https://trello.com/c/jIcigFBL/413-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%B1%D0%B0%D0%BB%D0%B0%D0%BD%D1%81%D0%B0-%D0%BF%D0%BE-%D0%BA%D0%B0%D0%B6%D0%B4%D0%BE%D0%BC%D1%83-%D1%81%D1%87%D1%91%D1%82%D1%83-sidebar
> update balances api

- app/views/api/v1/invoices/_invoice_item.json.jbuilder
- spec/requests/api/v1/invoices/show_spec.rb
https://trello.com/c/uUwxiNdd/477-invoices-show-items
> fix invoices api

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/bank_accounts_controller.rb
- app/controllers/invoices_controller.rb
- app/models/invoice_item.rb
- lib/russian_central_bank_safe.rb
- spec/features/delete_transaction_spec.rb
- spec/features/invoices/index_spec.rb
- spec/features/unsubscribes_spec.rb
- spec/models/statistic_data/columns_chart_spec.rb
- spec/requests/api/v1/bank_accounts/index_spec.rb
- spec/requests/api/v1/invoices/create_spec.rb
- spec/support/capybara.rb
https://trello.com/c/4f4ZEGIq/439-fix-failed-specs-deprecations
> fix broken specs, warnings and deprecations

- .ruby-gemset
- config/deploy/production.rb
- config/unicorn/production.rb
https://trello.com/c/5xWFa6cu/481-%D0%BD%D0%B0%D1%81%D1%82%D1%80%D0%BE%D0%B8%D1%82%D1%8C-%D0%BD%D0%BE%D0%B2%D1%8B%D0%B9-%D0%BF%D1%80%D0%BE%D0%B4%D0%B0%D0%BA%D1%88%D0%B5%D0%BD-%D1%81%D0%B5%D1%80%D0%B2%D0%B5%D1%80
> Production deploy fixes

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/invoices_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/models/invoice.rb
- app/models/profile.rb
- lib/nested_errors.rb
- spec/requests/api/v1/invoices/create_spec.rb
- spec/requests/api/v1/users/profile_spec.rb
https://trello.com/c/qVXl48fU/483-%D0%BF%D1%80%D0%BE%D1%84%D0%B8%D0%BB%D1%8C-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%B0%D0%BB%D0%B8%D0%B4%D0%B0%D1%86%D0%B8%D1%8E-%D1%82%D0%B5%D0%BB%D0%B5%D1%84%D0%BE%D0%BD%D0%BD%D0%BE%D0%B3%D0%BE-%D0%BD%D0%BE%D0%BC%D0%B5%D1%80%D0%B0
> fix with nested attributes, update invoices and profile api

- app/controllers/api/v1/invoices_controller.rb
- app/policies/invoice_policy.rb
- config/routes.rb
- spec/requests/api/v1/invoices/update_spec.rb
https://trello.com/c/rmE5blDM/462-invoices-edit
>  feat(Invoice): add update to api

- app/controllers/api/v1/invoices_controller.rb
- app/controllers/api/v1/users_controller.rb
- app/models/invoice.rb
- app/policies/invoice_policy.rb
- app/views/api/v1/invoices/_invoice_item.json.jbuilder
- lib/nested_errors.rb
- spec/factories.rb
- spec/features/change_profile_spec.rb
- spec/requests/api/v1/invoices/create_spec.rb
- spec/requests/api/v1/invoices/update_spec.rb
- spec/requests/api/v1/users/profile_spec.rb
https://trello.com/c/Rs36Jktk/465-invoices-edit-edit-items
> fix nested errors, update invoices and users api

- app/controllers/api/v1/invoices_controller.rb
- app/controllers/invoices_controller.rb
- app/models/bank_account.rb
- app/models/invoice.rb
- app/policies/invoice_policy.rb
- app/views/api/v1/invoices/_invoice.json.jbuilder
- app/views/invoices/_form.html.slim
- app/views/invoices/_invoice_body.html.slim
- db/migrate/20180531072229_add_bank_account_to_invoices.rb
- db/schema.rb
- spec/factories/invoices.rb
- spec/features/invoices/create_spec.rb
- spec/models/bank_account_spec.rb
- spec/models/invoice_spec.rb
https://trello.com/c/sZOhiIDr/491-%D0%BF%D1%80%D0%B8-%D1%81%D0%BE%D0%B7%D0%B4%D0%B0%D0%BD%D0%B8%D0%B8-%D0%B8%D0%BD%D0%B2%D0%BE%D0%B9%D1%81%D0%B0-%D0%BD%D1%83%D0%B6%D0%BD%D0%BE-%D0%B8%D0%BC%D0%B5%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B2%D1%8B%D0%B1%D0%B8%D1%80%D0%B0%D1%82%D1%8C-bank-account-%D0%BD%D0%B0-%D0%BA%D0%BE%D1%82%D0%BE%D1%80%D1%8B%D0%B9-%D0%B2%D1%8B%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D1%8F%D0%B5%D1%82%D1%81%D1%8F-%D1%8D%D1%82%D0%BE%D1%82-%D0%B8%D0%BD%D0%B2%D0%BE%D0%B9%D1%81
> feat(Invoice): add bank account, update api

- app/controllers/api/v1/base_controller.rb
- app/controllers/api/v1/currencies_controller.rb
- config/routes.rb
- spec/requests/api/v1/currencies/index_spec.rb
https://trello.com/c/PJtdHH37/517-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-currency-input
> Move currencies API to separate controller

- .rubocop.yml
- app/controllers/api/v1/bank_accounts_controller.rb
- app/models/bank_account.rb
- app/views/api/v1/bank_accounts/_bank_account.json.jbuilder
- config/routes.rb
- spec/factories.rb
- spec/factories/organizations.rb
- spec/requests/api/v1/bank_accounts/visible_spec.rb
https://trello.com/c/ndUS8P1y/525-%D0%B8%D1%81%D0%BF%D1%80%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D1%81%D1%87%D0%B5%D1%82%D0%BE%D0%B2
> Update bank accounts

- app/helpers/layout_helper.rb
- app/models/concerns/period.rb
- app/models/invoice.rb
- app/models/transaction.rb
- app/views/api/v1/invoices/_short_invoice.json.jbuilder
- app/views/api/v1/transactions/_transaction.json.jbuilder
- lib/time_range.rb
- spec/factories.rb
- spec/factories/transactions.rb
- spec/requests/api/v1/transactions/create_spec.rb
- spec/requests/api/v1/transactions/show_spec.rb
- spec/support/matchers/json_matchers.rb
- spec/support/request_helpers/json_helpers.rb
https://trello.com/c/73YVT99U/547-%D0%BF%D1%80%D0%B8-complete-%D0%B8%D0%BD%D0%B2%D0%BE%D0%B9%D1%81%D0%B0-%D0%BE%D0%BD-%D0%BD%D0%B5-%D0%BF%D0%BE%D0%BC%D0%B5%D1%87%D0%B0%D0%B5%D1%82%D1%81%D1%8F-%D0%BA%D0%B0%D0%BA-%D0%BE%D0%BF%D0%BB%D0%B0%D1%87%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9
> Complete invoice

- Gemfile
- Gemfile.lock
- app/controllers/api/v1/organizations_controller.rb
- app/models/organization.rb
- app/serializers/application_serializer.rb
- app/serializers/organization_serializer.rb
- app/views/api/v1/organizations/_organization.json.jbuilder
- app/views/api/v1/organizations/index.json.jbuilder
- app/views/api/v1/organizations/show.json.jbuilder
- config/initializers/active_model_serializers.rb
- spec/factories/organizations.rb
- spec/factories/users.rb
- spec/requests/api/v1/organizations/create_spec.rb
- spec/requests/api/v1/organizations/destroy_spec.rb
- spec/requests/api/v1/organizations/index_spec.rb
- spec/requests/api/v1/organizations/show_spec.rb
- spec/requests/api/v1/organizations/update_spec.rb
- spec/support/matchers/json_matchers.rb
https://trello.com/c/1N7GfsPn/520-manage-organization-edit
> update organizations api

- app/controllers/api/v1/transactions_controller.rb
- app/models/transaction.rb
- app/models/transactions_summary.rb
- app/policies/transaction_policy.rb
- app/serializers/application_serializer.rb
- app/serializers/transactions_summary_serializer.rb
- config/routes.rb
- spec/requests/api/v1/transactions/summary_spec.rb
https://trello.com/c/o45ZPaeo/580-transaction-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80%D0%B0%D1%86%D0%B8%D0%B8-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D0%B8-%D0%BD%D0%B5%D0%BE%D0%B1%D1%85%D0%BE%D0%B4%D0%B8%D0%BC%D0%BE-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%82%D1%8C-%D0%B2%D0%BD%D0%B8%D0%B7%D1%83-%D1%81%D1%82%D1%80%D0%B0%D0%BD%D0%B8%D1%86%D1%8B-%D0%BE%D0%B1%D1%89%D1%83%D1%8E-%D0%B8%D1%82%D0%BE%D0%B3%D0%BE%D0%B2%D1%83%D1%8E-%D0%B8%D0%BD%D1%84%D0%BE%D1%80%D0%BC%D0%B0%D1%86%D0%B8%D1%8E-%D0%BF%D0%BE-%D1%82%D1%80%D0%B0%D0%BD%D0%B7%D0%B0%D0%BA%D1%86%D0%B8%D1%8F%D0%BC-%D0%B8%D1%82%D0%BE%D0%B3%D0%BE-%D0%B2%D1%85%D0%BE%D0%B4
> Transactions summary API

- app/controllers/customers_controller.rb
- spec/features/create_customer_by_transaction_spec.rb
https://trello.com/c/Fci6Sk9b/604-transactions-fix-create-customer-from-transactions
> fix(Transactions): create customer

- app/models/category.rb
- spec/factories/organizations.rb
- spec/requests/api/v1/categories/index_spec.rb
https://trello.com/c/AvIouB49/605-%D0%BA%D0%B0%D1%82%D0%B5%D0%B3%D0%BE%D1%80%D0%B8%D0%B8-%D0%B2-%D0%B4%D1%80%D0%BE%D0%BF%D0%B1%D0%BE%D0%BA%D1%81%D0%B0%D1%85-%D1%81%D0%BE%D1%80%D1%82%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BF%D0%BE-%D0%B0%D0%BB%D1%84%D0%B0%D0%B2%D0%B8%D1%82%D1%83
> update categories ordering

- app/controllers/api/v1/bank_accounts_controller.rb
- app/views/api/v1/bank_accounts/_bank_account.json.jbuilder
- config/routes.rb
- spec/requests/api/v1/bank_accounts/sort_spec.rb
- spec/requests/api/v1/bank_accounts/update_position_spec.rb
https://trello.com/c/QS2S5p83/529-bank-accounts-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B2%D0%BE%D0%B7%D0%BC%D0%BE%D0%B6%D0%BD%D0%BE%D1%81%D1%82%D1%8C-%D0%B2%D1%8B%D1%81%D1%82%D0%B0%D0%B2%D0%BB%D0%B5%D0%BD%D0%B8%D1%8F-%D0%BF%D0%BE%D1%80%D1%8F%D0%B4%D0%BA%D0%B0-%D1%81%D1%87%D0%B5%D1%82%D0%BE%D0%B2
> feat: add bank accounts sorting

- app/controllers/api/v1/statistics_controller.rb
- app/models/statistic_data/helpers.rb
- app/models/statistic_data/round_chart.rb
- app/policies/statistic_policy.rb
- app/serializers/income_categories_statistic_serializer.rb
- config/routes.rb
- spec/models/statistic_data/round_chart_spec.rb
- spec/requests/api/v1/statistics/income_categories_spec.rb
https://trello.com/c/zDfRvMRR/608-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-income-by-categories
> Income categories chart

- app/controllers/api/v1/statistics_controller.rb
- app/policies/statistic_policy.rb
- app/serializers/income_customers_statistic_serializer.rb
- config/routes.rb
- spec/requests/api/v1/statistics/income_customers_spec.rb
https://trello.com/c/tFq5RUPD/610-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-income-by-customers
> Add income by customers chart

- app/controllers/api/v1/statistics_controller.rb
- app/policies/statistic_policy.rb
- app/serializers/customers_statistic_serializer.rb
- config/routes.rb
- spec/requests/api/v1/statistics/expense_customers_spec.rb
https://trello.com/c/PZsb5BDl/611-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-expense-by-customers
> Add expense by customers chart

- app/controllers/api/v1/statistics_controller.rb
- app/policies/statistic_policy.rb
- app/serializers/categories_statistic_serializer.rb
- config/routes.rb
- spec/requests/api/v1/statistics/expense_categories_spec.rb
https://trello.com/c/JBAqMk2d/609-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-expense-by-categories
> expense by categories chart api

- app/controllers/api/v1/statistics_controller.rb
- app/models/statistic_data/columns_chart.rb
- app/models/statistic_data/helpers.rb
- app/models/statistic_data/round_chart.rb
- app/policies/statistic_policy.rb
- app/serializers/categories_statistic_serializer.rb
- app/serializers/customers_balances_statistic_serializer.rb
- app/serializers/customers_statistic_serializer.rb
- config/routes.rb
- spec/models/statistic_data/round_chart_spec.rb
- spec/requests/api/v1/statistics/balances_by_customers_spec.rb
- spec/requests/api/v1/statistics/expense_categories_spec.rb
- spec/requests/api/v1/statistics/expense_customers_spec.rb
- spec/requests/api/v1/statistics/income_categories_spec.rb
- spec/requests/api/v1/statistics/income_customers_spec.rb
- spec/requests/api/v1/statistics/totals_by_customers_spec.rb
https://trello.com/c/4eMth7XL/612-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-total-by-customers
> feat: add totals and balances by customers charts

- app/serializers/categories_statistic_serializer.rb
- app/serializers/customers_balances_statistic_serializer.rb
- app/serializers/customers_statistic_serializer.rb
- spec/requests/api/v1/statistics/balances_by_customers_spec.rb
- spec/requests/api/v1/statistics/expense_categories_spec.rb
- spec/requests/api/v1/statistics/expense_customers_spec.rb
- spec/requests/api/v1/statistics/income_categories_spec.rb
- spec/requests/api/v1/statistics/income_customers_spec.rb
- spec/requests/api/v1/statistics/totals_by_customers_spec.rb
https://trello.com/c/0NYwQiqP/616-statistics-%D0%BE%D0%BF%D1%82%D0%B8%D0%BC%D0%B8%D0%B7%D0%B8%D1%80%D0%BE%D0%B2%D0%B0%D1%82%D1%8C-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B5%D0%BD%D0%B8%D0%B5-%D0%BA%D1%80%D1%83%D0%B3%D0%BE%D0%B2%D1%8B%D1%85-%D0%B4%D0%B8%D0%B0%D0%B3%D1%80%D0%B0%D0%BC%D0%BC
> update charts api, fix specs

- app/models/date_logic.rb
https://trello.com/c/7Qv4qfKJ/622-%D0%BF%D0%BE%D1%84%D0%B8%D0%BD%D0%B8%D1%82%D1%8C-%D0%B3%D0%BB%D0%B0%D0%B2%D0%BD%D1%8B%D0%B9-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-balance-%D0%BF%D1%80%D0%B8-%D0%B2%D1%8B%D0%B1%D0%BE%D1%80%D0%B5-years-%D0%BE%D1%82%D0%BE%D0%B1%D1%80%D0%B0%D0%B6%D0%B0%D1%82%D1%8C-%D0%B4%D0%B0%D0%BD%D0%BD%D1%8B%D0%B5-%D1%81%D1%80%D0%B0%D0%B7%D1%83-%D0%BD%D0%B0-5-%D0%BF%D0%BE%D1%81%D0%BB%D0%B5%D0%B4%D0%BD%D0%B8%D1%85-%D0%BB%D0%B5%D1%82
> update balance chart

- app/controllers/api/v1/statistics_controller.rb
- app/controllers/statistics_controller.rb
- app/models/statistic_data/columns_chart.rb
- app/policies/statistic_policy.rb
- app/serializers/customers_by_months_statistic_serializer.rb
- config/routes.rb
- spec/models/statistic_data/columns_chart_spec.rb
- spec/requests/api/v1/statistics/expense_customers_by_months_spec.rb
- spec/requests/api/v1/statistics/income_customers_by_months_spec.rb
https://trello.com/c/b00Dvk3L/619-statistics-%D0%B4%D0%BE%D0%B1%D0%B0%D0%B2%D0%B8%D1%82%D1%8C-%D0%B3%D1%80%D0%B0%D1%84%D0%B8%D0%BA-income-expense-by-customers
> add customers by months api

- Gemfile
- Gemfile.lock
- spec/features/accept_organization_invitation_spec.rb
- spec/features/delete_transaction_spec.rb
- spec/features/invoices/create_spec.rb
- spec/features/invoices/delete_spec.rb
- spec/features/invoices/index_spec.rb
- spec/features/remove_member_spec.rb
- spec/features/transactions/filter/filter_by_period_spec.rb
- spec/features/transactions/filter/filter_spec.rb
- spec/features/update_transaction_spec.rb
- spec/requests/api/v1/currencies/index_spec.rb
- spec/requests/api/v1/statistics/totals_by_customers_spec.rb
- spec/support/capybara.rb
Test environment update: replacing capybara-webkit with webdrivers.
> fix: migrate from capybara-webkit to webdrivers

- spec/features/transactions_sort_spec.rb
- spec/support/shared_examples/flowable.rb
- spec/support/shared_examples/sortable.rb
Now rounding problem fix. Also fix mistake css selector.
> fix: update tests for fix mistake
